# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  start_lat: <%= ENV["START_LAT"] %>
  start_lng: <%= ENV["START_LNG"] %>
  admin_company: <%= ENV["ADMIN_COMPANY"] %>
  admin_company_description: <%= ENV["ADMIN_COMPANY_DESCRIPTION"] %>
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MAIL_USERNAME"] %>
  email_provider_password: <%= ENV["MAIL_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  install_timezone: <%= ENV["INSTALL_TIMEZONE"] %>
  upload_limit_size: <%= ENV["UPLOAD_LIMIT_SIZE"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default